### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by axtens** [tani/gas-minimal-boilerplate#1]
C:\TMP>git clone https://github.com/ta2gch/gas-minimal-boilerplate.git FooBar2
Cloning into 'FooBar2'...
remote: Enumerating objects: 24, done.
remote: Total 24 (delta 0), reused 0 (delta 0), pack-reused 24
Unpacking objects: 100% (24/24), done.

C:\TMP>cd FooBar2

C:\TMP\FooBar2>dir
 Volume in drive C is OS
 Volume Serial Number is 2652-D365

 Directory of C:\TMP\FooBar2

04/03/2019  10:13 PM    <DIR>          .
04/03/2019  10:13 PM    <DIR>          ..
04/03/2019  10:13 PM                64 .clasp.json
04/03/2019  10:13 PM               942 .gitignore
04/03/2019  10:13 PM                95 appsscript.json
04/03/2019  10:13 PM             1,073 LICENSE
04/03/2019  10:13 PM           187,231 package-lock.json
04/03/2019  10:13 PM               885 package.json
04/03/2019  10:13 PM               768 README.md
04/03/2019  10:13 PM    <DIR>          src
04/03/2019  10:13 PM               478 webpack.config.js
               8 File(s)        191,536 bytes
               3 Dir(s)  152,981,151,744 bytes free

C:\TMP\FooBar2>npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 541 packages from 339 contributors and audited 6060 packages in 13.686s
found 17 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

C:\TMP\FooBar2>npm audit fix
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bugma\AppData\Roaming\npm-cache\_logs\2019-04-03T14_13_48_508Z-debug.log

**Comment by tani** [comment]
Thank you for contacting us.
I guess this error is caused by the `fsevents`. This package, however, is **not** required directly by our package. You don't need to do `npm audit fix`, It runs perfectly without problems.

Cheers.
